### ISSUE TITLE
Duplicates!

### ISSUE THREAD

**Issue by DhrubajitPC** [skewedlines/brat#1]
there are still duplicate annotations everytime i run the cmd.. My corpus is corrupted

**Comment by jiahaog** [comment]
Are you using windows?

**Comment by DhrubajitPC** [comment]
i am using mac.. what happens is everytime i change a line and annotate differently, it overlaps with the previous one.. this is what i mean by duplicate.. also.. its possible to sabo someone by deleting there annotations..

**Comment by jiahaog** [comment]
I fixed this yesterday already, I'm not sure why you're having an error. Are the locations of the annotations correct? (Meaning what you do locally is reflected correctly online)

Make sure you're running the latest version by running:

```
$ npm install -g brat
```

**Comment by DhrubajitPC** [comment]
there was an issue with my text editor... it changed some of the texts.. which resulted in incorrect and overlapping annotations...sorry for the alarm...

**Comment by jiahaog** [comment]
Haha yay!
